version: "3"
services:
 mymongodb:
   image: mongo:latest
   container_name: "mymongodb"
   ports:
     - 27017:27017
 mongo_seed:
    build: ./dbseed
    links:
      - mymongodb
 quiz-app-final-container:
   image: omkarlubal/quizapp_quiz-app-final-container:latest
   container_name: "quizapp_quiz-app-final-container"
   ports:
     - 8080:8080
   links:
     - mymongodb